[package]
name = "mygrid"
version = "3.1.0"
edition = "2021"

[dependencies]
md-5 = "0.10.6"
chrono = "0.4"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_with = { version = "3.16", features = ["chrono"] }
ureq = "3.1"
toml = "0.9"
glob = "0.3"
lettre = "0.11"
log4rs = "1.4"
log = "0.4"
thiserror = "2.0"
anyhow = "1.0"
