[charge]
soc_kwh = 0.1659             # kWh per SoC unit (bat_capacity / 100)

[fox_ess]

[mail]
smtp_endpoint     = "email-smtp.eu-north-1.amazonaws.com"
from              = "MyGrid <peter.steneld@gridfire.org>"
to                = "Peter Steneld <peter.steneld@gmail.com>"

[files]
schedule_dir = "/home/petste/MyGridScheduler/schedule/"
manual_file = "/home/petste/MyGrid/manual_dates.json"

[general]
# debug_run_time    = "2025-10-26T03:05:00+01:00"
log_path          = "/home/petste/MyGrid/logs/mygrid.log"
log_level         = "Info"
log_to_stdout     = false
debug_mode        = false
